version: "3.7"

services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8888
    volumes:
      - ./:/src/
    ports:
      - "8888:8888"